- name: Deploy CNV on OCP Cluster
  import_tasks: deploy_cnv.yml
  when: deploy_type == 'upi' or deploy_type == 'ipi'

- name: Deploy CNV on Edge1 SNO Cluster
  import_tasks: deploy_cnv_sno.yml
  when: deploy_type == 'sno'