- name: Deploy CNV on OCP Cluster
  import_tasks: deploy_cnv.yml
  when: ocp4_aio_deploy_type == 'upi' or ocp4_aio_deploy_type == 'ipi'

- name: Deploy CNV on Edge1 SNO Cluster
  import_tasks: deploy_cnv_sno.yml
  when: ocp4_aio_deploy_type == 'sno'